//
//  ContentView.swift
//  go-sdk-demo-app-ios-swift
//
//  Created by Mehdi Kouhen on 28/02/2023.
//

import SwiftUI
import SealdSdk
import JWT

func runTests() {
    print("SDK DEMO START")
    // Seald account infos:
    // First step with Seald: https://docs.seald.io/en/sdk/guides/1-quick-start.html
    // Create a team here: https://www.seald.io/create-sdk
    let apiURL = "https://api-dev.soyouz.seald.io/"
    let appId = "00000000-0000-1000-a000-7ea300000018"
    let JWTSharedSecretId = "00000000-0000-1000-a000-7ea300000019"
    let JWTSharedSecret = "o75u89og9rxc9me54qxaxvdutr2t4t25ozj4m64utwemm0osld0zdb02j7gv8t7x"
    
    // The Seald SDK uses a local database that will persist on disk.
    // When instantiating a SealdSDK, it is highly recommended to set a symmetric key to encrypt this database.
    // This demo will use a fixed key. It should be generated at signup, and retrieved from your backend at login.
    let databaseEncryptionKeyB64 = "V4olGDOE5bAWNa9HDCvOACvZ59hUSUdKmpuZNyl1eJQnWKs5/l+PGnKUv4mKjivL3BtU014uRAIF2sOl83o6vQ"
    
    // Find database Path
    let paths = NSSearchPathForDirectoriesInDomains(.documentDirectory, .userDomainMask, true)
    let documentsDirectory = paths[0]
    let sealdDir = "\(documentsDirectory)/seald-swift"
    
    // Delete local database from previous run
    let fileManager = FileManager.default
    try? fileManager.removeItem(atPath: sealdDir)
    
    // Seald uses JWT to manage licenses and identity.
    // JWTs should be generated by your backend, and sent to the user at signup.
    // The JWT secretId and secret can be generated from your administration dashboard. They should NEVER be on client side.
    // However, as this is a demo without a backend, we will use them on the frontend.
    // JWT documentation: https://docs.seald.io/en/sdk/guides/jwt.html
    // identity documentation: https://docs.seald.io/en/sdk/guides/4-identities.html
    let jwtBuilder = JWTBuilder(JWTSharedSecretId: JWTSharedSecretId, JWTSharedSecret: JWTSharedSecret)

    
    // let's instantiate 3 SealdSDK. They will correspond to 3 users that will exchange messages.
    let sdk1 = try! SealdSdk.init(apiUrl: apiURL, appId: appId, dbPath: "\(sealdDir)/sdk1", dbb64SymKey: databaseEncryptionKeyB64, instanceName: "User1", logLevel: -1, logNoColor: true, encryptionSessionCacheTTL: 0, keySize: 4096)
    let sdk2 = try! SealdSdk.init(apiUrl: apiURL, appId: appId, dbPath: "\(sealdDir)/sdk2", dbb64SymKey: databaseEncryptionKeyB64, instanceName: "User2", logLevel: -1, logNoColor: true, encryptionSessionCacheTTL: 0, keySize: 4096)
    let sdk3 = try! SealdSdk.init(apiUrl: apiURL, appId: appId, dbPath: "\(sealdDir)/sdk3", dbb64SymKey: databaseEncryptionKeyB64, instanceName: "User3", logLevel: -1, logNoColor: true, encryptionSessionCacheTTL: 0, keySize: 4096)
    
    // retrieve info about current user before creating a user should return null
    let retrieveNoAccount = sdk1.getCurrentAccountInfo()
    assert(retrieveNoAccount?.deviceId == nil)
    
    // Create the 3 accounts. Again, the signupJWT should be generated by your backend
    let user1AccountInfo = try! sdk1.createAccount(withSignupJwt: jwtBuilder.signupJWT(), deviceName: "MyDeviceName", displayName: "User1", expireAfter: 5 * 365 * 24 * 60 * 60)
    let user2AccountInfo = try! sdk2.createAccount(withSignupJwt: jwtBuilder.signupJWT(), deviceName: "MyDeviceName", displayName: "User2", expireAfter: 5 * 365 * 24 * 60 * 60)
    let user3AccountInfo = try! sdk3.createAccount(withSignupJwt: jwtBuilder.signupJWT(), deviceName: "MyDeviceName", displayName: "User3", expireAfter: 5 * 365 * 24 * 60 * 60)
    
    // retrieve info about current user:
    let retrieveAccountInfo = sdk1.getCurrentAccountInfo()
    assert(retrieveAccountInfo != nil)
    assert(retrieveAccountInfo?.userId == user1AccountInfo.userId)
    assert(retrieveAccountInfo?.deviceId == user1AccountInfo.deviceId)
    
    // Create group: https://docs.seald.io/sdk/guides/5-groups.html
    let groupName = "group-1"
    let groupMembers = [user1AccountInfo.userId!]
    let groupAdmins = [user1AccountInfo.userId!]
    let groupId = try! sdk1.createGroup(groupName, members: groupMembers, admins: groupAdmins)
    
    let error: NSErrorPointer
    // Manage group members and admins
    sdk1.addGroupMembers(withGroupId: groupId, membersToAdd: [user2AccountInfo.userId!], adminsToSet: [], error: error) // Add user2 as group member
    assert(error == nil)
    sdk1.addGroupMembers(withGroupId: groupId, membersToAdd: [user3AccountInfo.userId!], adminsToSet: [user3AccountInfo.userId!], error: error) // user1 add user3 as group member and group admin
    assert(error == nil)
    sdk3.removeGroupMembers(withGroupId: groupId, membersToRemove: [user2AccountInfo.userId!], error: error) // user3 can remove user2
    assert(error == nil)
    sdk3.setGroupAdminsWithGroupId(groupId, addToAdmins: [], removeFromAdmins: [user1AccountInfo.userId!], error: error) // user3 can remove user1 from admins
    assert(error == nil)

    
    // Create encryption session: https://docs.seald.io/sdk/guides/6-encryption-sessions.html
    let recipient = [user1AccountInfo.userId!, user2AccountInfo.userId!, groupId]
    let es1SDK1 = try! sdk1.createEncryptionSession(withRecipients: recipient, useCache: true) // user1, user2, and group as recipients

    // The io.seald.seald_sdk.EncryptionSession object can encrypt and decrypt for user1
    let initialString = "a message that needs to be encrypted!"
    let encryptedMessage = try! es1SDK1.encryptMessage(initialString)
    let decryptedMessage = try! es1SDK1.decryptMessage(encryptedMessage)
    assert(initialString == decryptedMessage)



    /*
    let members = [userId]
    let groupId = try? seald.createGroup("amzingGroupName", members: members, admins: members) // TODO: try!
    print("groupId \(groupId)")

    let es1SDK1 = try! seald.createEncryptionSession(members, useCache: true)

    let encryptedMessage = try! es1SDK1.encryptMessage("coucou")
    print("encryptedMessage \(encryptedMessage)")

    let decryptedMessage = try! es1SDK1.decryptMessage(encryptedMessage)
    print("decryptedMessage \(decryptedMessage)")
    */
    print("SDK DEMO END")
}

struct ContentView: View {
    var body: some View {
        Text("Hello, world!")
            .padding()
            .onAppear{
                runTests()
            }
    }
}

struct ContentView_Previews: PreviewProvider {
    static var previews: some View {
        ContentView()
    }
}
